import sqlite3
import json
from backtester import Backtester
from agent.memory import MemoryManager
from agent.brain import TradingBrain

class Optimizer:
    def __init__(self):
        self.memory = MemoryManager()
        self.brain = TradingBrain()
        self.db_path = self.memory.db_path

    def get_win_rate(self):
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute("SELECT result FROM trades WHERE result IN ('success', 'failure')")
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return 0.0, 0

        successes = sum(1 for r in rows if r[0] == 'success')
        total = len(rows)
        return (successes / total), total

    def run_loop(self, target_win_rate=0.85, max_iterations=3):
        rules_context = ""

        for iteration in range(1, max_iterations + 1):
            print(f"\n========== OPTIMIZATION ITERATION {iteration} ==========")

            # Clear database for the new iteration to calculate purely based on this iteration
            # But keep Mempalace failures for cumulative learning
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM trades")
            cursor.execute("DELETE FROM reflections")
            conn.commit()
            conn.close()

            # Run backtester
            bt = Backtester(rules_context=rules_context)
            # Run on a smaller subset for speed during dev:
            # BTC and ETH on 15m.
            bt.run(symbols=['BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'BNB/USDT', 'XRP/USDT', 'ADA/USDT', 'DOGE/USDT', 'AVAX/USDT', 'LINK/USDT', 'MATIC/USDT', 'DOT/USDT', 'TRX/USDT', 'LTC/USDT', 'SHIB/USDT', 'UNI/USDT', 'ATOM/USDT', 'XMR/USDT', 'ETC/USDT', 'TON/USDT', 'ALGO/USDT'], timeframes=['15m', '1h'])

            # Evaluate
            win_rate, total_trades = self.get_win_rate()
            print(f"\nIteration {iteration} Complete. Total Trades: {total_trades}, Win Rate: {win_rate:.2%}")

            if win_rate >= target_win_rate:
                print("Target Win Rate Achieved! Optimization Complete.")
                break

            if total_trades == 0:
                print("No trades were taken. The rules might be too strict. Adjusting...")
                rules_context = "Previous rules resulted in 0 trades. Please relax the strictness slightly while maintaining 1:2 RR."
                continue

            print("Win rate below target. Reflecting on failures...")
            failures = self.memory.query_patterns('failures')
            if failures:
                # Take the most recent failures to not overflow context
                recent_failures = failures[-10:]
                new_rules = self.brain.reflect_on_failure(recent_failures)
                if new_rules:
                    print("New Rules generated by Brain:")
                    for rule in new_rules:
                        print(f" - {rule}")
                    rules_context = "\n".join(new_rules)
                else:
                    print("Failed to generate new rules.")

if __name__ == "__main__":
    opt = Optimizer()
    # Limiting iterations to 2 for the sandbox environment time constraints
    opt.run_loop(target_win_rate=0.85, max_iterations=2)
